import os

from dotenv import load_dotenv

load_dotenv()

NEXTCLOUD_WEBDAV_URL = os.getenv("NEXTCLOUD_WEBDAV_URL")
NEXTCLOUD_USERNAME = os.getenv("NEXTCLOUD_USERNAME")
NEXTCLOUD_PASSWORD = os.getenv("NEXTCLOUD_PASSWORD")
NEXTCLOUD_PHOTOS_PATH = os.getenv("NEXTCLOUD_PHOTOS_PATH")
